#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'closure-linter==2.2.7','console_scripts','fixjsstyle'
__requires__ = 'closure-linter==2.2.7'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('closure-linter==2.2.7', 'console_scripts', 'fixjsstyle')()
)
